---
# tasks file for Ansible-Docker
- name: Install Prerequisite Packages
  apt:
    update_cache: yes
    pkg: "{{ DOCKER_PREREQUISITES }}"
    state: present
  when: ansible_os_family == 'Debian'

- name: Check if {{ DOCKER_CONFIG_DIR }} Exists
  stat:
    path: "{{ DOCKER_CONFIG_DIR }}"
  register: docker_config_dir

- name: Check if {{ DOCKER_CONTAINER_LOGS_DIR }} Exists
  stat:
    path: "{{ DOCKER_CONTAINER_LOGS_DIR }}"
  register: docker_container_logs_dir

- name: Create Directory {{ DOCKER_CONFIG_DIR }}
  file:
    path: "{{ DOCKER_CONFIG_DIR }}"
    state: directory
    mode: 0755
  when: not docker_config_dir.stat.exists

- name: Create Directory {{ DOCKER_CONTAINER_LOGS_DIR }}
  file:
    path: "{{ DOCKER_CONTAINER_LOGS_DIR }}"
    state: directory
    mode: 0755
  when: (not docker_container_logs_dir.stat.exists) and (DOCKER_ENABLE_LOGGING_SYSLOG)

- name: Add Docker Repository Key
  apt_key:
    url: "{{ DOCKER_APT_KEY }}"
    state: present
  when: ansible_os_family == 'Debian'

- name: Setup Docker Package Repository
  template:
    src: "templates/docker-ce.list.j2"
    dest: "/etc/apt/sources.list.d/docker-ce.list"
  when: ansible_os_family == 'Debian'

- name: Install Docker
  apt:
    update_cache: yes
    pkg: "{{ DOCKER_PKG }}"
    state: present
  when: ansible_os_family == 'Debian'

- name: Write Docker Configuration File
  template:
    src: "templates/etc/docker/daemon.json.j2"
    dest: "{{ DOCKER_CONFIG_DIR }}/daemon.json"
  notify: Restart Docker
